name: E2E testing

on:
  schedule:
    - cron: '42,56 16,17 * * *'

jobs:
  test_schedule:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install behave
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with behave
        run: |
          behave